### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by natdm** [ray-x/cmp-treesitter#2]
Maybe add examples on how this is useful. Between all the sources that cmp can have, I can't legitimately tell what this does for me. I love both cmp and treesitter, so I'd love to see if I get benefit from this.

**Comment by wimstefan** [comment]
I can second that :+1: 
I got curious and installed it but after having configured it it was never invoked ... so some short explanation of how it works and what it is thought for would be quite helpful ;)

**Comment by wimstefan** [comment]
Thanks a lot for the screenshots!
Apparently I've configured the source wrong since I don't get the same completion items as shown in those screenshots ... 🤔

Here's my relevant config:
```lua
use {
  'hrsh7th/nvim-cmp',
  requires = {
    {
      'ray-x/cmp-treesitter',
      after = 'nvim-cmp',
    },
    -- ...
  },
  config = function()
    require('cmp').setup({
      --- ...
      formatting = {
        format = function(entry, vim_item)
          vim_item.menu = ({
            buffer = '[Buffer]',
            vsnip = '[Snippet]',
            nvim_lsp = '[LSP]',
            nvim_lua = '[LUA]',
            omni = '[Omni]',
            path = '[Filesystem]',
            spell = '[Spelling]',
            treesitter = '[TS]',
          })[entry.source.name]
          vim_item.kind = vim.lsp.protocol.CompletionItemKind[vim_item.kind] .. ' ' .. vim_item.kind
          return vim_item
        end
      },
      --- ...
      sources = cmp.config.sources({
        {name = 'omni'},
        {name = 'treesitter'}
      }, {
        {name = 'nvim_lua'},
        {name = 'nvim_lsp'},
        {name = 'vsnip'},
        {name = 'spell'}
      }, {
        {name = 'buffer',
          opts = {
            get_bufnrs = function()
              local bufs = {}
              for _, win in ipairs(vim.api.nvim_list_wins()) do
                bufs[vim.api.nvim_win_get_buf(win)] = true
              end
              return vim.tbl_keys(bufs)
            end
          }
        },
        {name = 'path'}
      })
      --- ...
    })
  end
}
```

**Comment by ray-x** [comment]
Maybe try this
```lua
      sources = cmp.config.sources({
        {name = 'omni'},
        {name = 'treesitter'},
        {name = 'nvim_lua'},
        {name = 'nvim_lsp'},
        {name = 'vsnip'},
        {name = 'spell'},
        {name = 'buffer',
          opts = {
            get_bufnrs = function()
              local bufs = {}
              for _, win in ipairs(vim.api.nvim_list_wins()) do
                bufs[vim.api.nvim_win_get_buf(win)] = true
              end
              return vim.tbl_keys(bufs)
            end
          }
        },
        {name = 'path'}
      })

```

**Comment by wimstefan** [comment]
This didn't help unfortunately :/

`CmpStatus` shows the `treesitter` source as `ready` though ...

**Comment by ray-x** [comment]
You can use minimum config and disable other sources so you know if it works.

**Comment by wimstefan** [comment]
After using a minimal nvim-cmp config with only cmp-treesitter configured I still don't get treesitter completion items.
I'll first wait and see whether @natdm is more successful ...

Many thanks for your efforts and willingness to look into my issue! 🙏

**Comment by ray-x** [comment]
There is a place you can print out debug info:

https://github.com/ray-x/cmp-treesitter/blob/0ba0a99b43420789740642f85e3fd076f1259418/lua/cmp_treesitter/treesitter.lua#L64

You can uncomment this line and see if there are anything printed out.

**Comment by wimstefan** [comment]
It's getting interesting :)
I've discovered that line already and uncommented it, disabled all other sources in the `nvim-cmp` configuration but still nothing - and  I really mean nothing. `CmpStatus` still shows `treesitter` as an available (and only) source but when I try to trigger completion with `<Tab>` nothing happens at all. There is still a fallback on omni-completion with `<C-x><C-o>` or `<C-n>` but I presume that has nothing to do with `nvim-cmp`?

**Comment by natdm** [comment]
<img width="433" alt="Screen Shot 2021-10-24 at 10 54 56 AM" src="https://user-images.githubusercontent.com/11272201/138606570-2b7ff744-bd71-414d-ba3e-5df5f40ebe78.png">
I went ahead and also added a menu of `tree` for mine (since changed to `tsit`) (I didn't know `cmp` could do that, it helps a lot) and I can see a *lot* of throughput. 

Thank you!!

**Comment by wimstefan** [comment]
Glad to hear that it worked for you :)
Would you mind sharing your working configuration?

**Comment by ray-x** [comment]
FYI: My neovim config  github.com/ray-x/nvim

**Comment by wimstefan** [comment]
> FYI: My neovim config github.com/ray-x/nvim

Thanks a lot - that's one of the reference configs I've already cloned and use to learn :)

**Comment by natdm** [comment]
Complete config, sorry it's so long. Probably have some relatively useless stuff.

```lua
local cmp = require 'cmp'
local luasnip = require("luasnip")
local lspkind = require "lspkind"
lspkind.init()
require("jira_source")

-- cmp-nvim-lsp
-- https://github.com/hrsh7th/cmp-nvim-lsp
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)

-- The following example advertise capabilities to `clangd`.
require'lspconfig'.clangd.setup {capabilities = capabilities}

local has_words_before = function()
    local line, col = unpack(vim.api.nvim_win_get_cursor(0))
    return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match("%s") == nil
end

cmp.setup({
    documentation = {zindex = 1000},
    snippet = {
        expand = function(args)
            require'luasnip'.lsp_expand(args.body)
        end
    },
    formatting = {
        -- Youtube: How to set up nice formatting for your sources.
        format = lspkind.cmp_format {
            with_text = true,
            menu = {
                buffer = "[buf]",
                nvim_lsp = "[lsp]",
                nvim_lua = "[nlua]",
                path = "[path]",
                luasnip = "[snip]",
                jira_issues = "[jira]",
                treesitter = '[tsit]'
            }
        }
    },

    experimental = {native_menu = false, ghost_text = true},
    mapping = {
        ['<C-d>'] = cmp.mapping.scroll_docs(-4),
        ['<C-f>'] = cmp.mapping.scroll_docs(4),
        ['<C-Space>'] = cmp.mapping.complete(), -- difference between complete and comfirm?
        ['<C-e>'] = cmp.mapping.close(),
        ['<C-y>'] = cmp.mapping.confirm({behavior = cmp.ConfirmBehavior.Replace, select = false}),
        ["<C-j>"] = cmp.mapping(function(fallback) -- Next input
            if cmp.visible() then
                cmp.select_next_item()
            elseif luasnip.expand_or_jumpable() then
                luasnip.expand_or_jump()
            elseif has_words_before() then
                cmp.complete()
            else
                fallback()
            end
        end, {"i", "s"}),

        ["<C-k>"] = cmp.mapping(function(fallback) -- Prev input
            if cmp.visible() then
                cmp.select_prev_item()
            elseif luasnip.jumpable(-1) then
                luasnip.jump(-1)
            else
                fallback()
            end
        end, {"i", "s"})
    },
    sources = {
        {name = 'luasnip'}, {name = 'nvim_lsp'}, {name = 'buffer', keyword_length = 3, max_item_count = 10}, {name = 'emoji'}, {name = 'path'},
        {name = "jira_issues"}, {name = "treesitter"}
    }
})
```

**Comment by wimstefan** [comment]
Thanks a lot @natdm !!!

Comparing your configuration (and rays-x' as well) to mine I can't spot the fault in my config ... still I don't get any results from the `treesitter` source. I think I'll give up for now and will try it later on again. Sometimes a little break does wonders and I might find out what I've done wrong so far ... ;)

Thanks for your support & patience guys 🙏

**Comment by TaminoSt** [comment]
Hey
I had the same problem. Everything seemed fine (no errors, cmp got the source), but there were no completion items. So i looked in the plugin. After a little bit of debugging I found out that the query was nil
https://github.com/ray-x/cmp-treesitter/blob/0ba0a99b43420789740642f85e3fd076f1259418/lua/cmp_treesitter/treesitter.lua#L43

So I looked in `:h get_query()` and saw `{query_name}  The name of the query (i.e. "highlights")`
When i changed `'Highlights'` to `'highlights'` and it worked.

**Comment by ray-x** [comment]
I updated to `hightlights` hope it works

**Comment by patrick96** [comment]
I can confirm pulling the new commit fixed the issue for me.

**Comment by wimstefan** [comment]
I can confirm as well that it's working now :)

Tremendous thanks to @z4m1n0 to dig that deep and find what the problem was and of course to @ray-x to implement the fix that quickly 🙏

**Comment by ray-x** [comment]
Thanks!
