### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by simonmandlik** [ray-x/cmp-treesitter#4]
Using treesitter completions with this plugins makes the whole insert mode quite laggy. Can anything be done about that or is it  unavoidable?

**Comment by ray-x** [comment]
what language server you are using? I don't not think it is from cmp-treesitter all current nodes will be cached instead of calculate each time

**Comment by zorgick** [comment]
I'm using this plugin in lua and typescript repos (the latter is a huge monorepo), I don't see any lagging. Usually treesitter completions are the first ones to resolve

**Comment by simonmandlik** [comment]
I can't reproduce either now. I will reopen if it comes up again and provide a MWE. Sorry for the trouble..
